name: WDD&mdash;330 Examples
url: "https://https://master.dbd5hsovljosn.amplifyapp.com"

sass:
  style: :nested

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0
